
import React, { useState } from 'react';
import { RappelTier } from '../types';
import { Card } from './ui/Card';
import Button from './ui/Button';
import Input from './ui/Input';
import { Icon } from './ui/Icon';

interface RappelSettingsProps {
    tiers: RappelTier[];
    onUpdateTiers: (tiers: RappelTier[]) => void;
}

const RappelSettings: React.FC<RappelSettingsProps> = ({ tiers, onUpdateTiers }) => {
    const [editableTiers, setEditableTiers] = useState<RappelTier[]>(tiers);
    const [newTier, setNewTier] = useState({ threshold: '', bonusPercentage: '' });

    const handleTierChange = (id: string, field: 'threshold' | 'bonusPercentage', value: string) => {
        const updatedTiers = editableTiers.map(tier =>
            tier.id === id ? { ...tier, [field]: parseFloat(value) || 0 } : tier
        );
        setEditableTiers(updatedTiers);
    };
    
    const handleNewTierChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setNewTier({ ...newTier, [e.target.name]: e.target.value });
    };

    const handleAddTier = () => {
        if (newTier.threshold && newTier.bonusPercentage) {
            const newTierData: RappelTier = {
                id: `tier-${Date.now()}`,
                threshold: parseFloat(newTier.threshold),
                bonusPercentage: parseFloat(newTier.bonusPercentage)
            };
            const updatedTiers = [...editableTiers, newTierData];
            setEditableTiers(updatedTiers);
            setNewTier({ threshold: '', bonusPercentage: '' });
        }
    };
    
    const handleDeleteTier = (id: string) => {
        const updatedTiers = editableTiers.filter(tier => tier.id !== id);
        setEditableTiers(updatedTiers);
    };
    
    const handleSaveChanges = () => {
        onUpdateTiers(editableTiers.sort((a,b) => a.threshold - b.threshold));
        // You would typically show a success notification here
        alert("Rappel settings saved!");
    };

    return (
        <div className="space-y-6 max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-800 dark:text-white">Rappel Settings</h2>
            <p className="text-gray-600 dark:text-gray-400">
                Configure the performance-based bonuses (rappels) for your sales team. Tiers are evaluated based on the total revenue generated by a salesperson in the last 12 months. The bonus is then calculated on that same 12-month revenue.
            </p>

            <Card>
                <div className="p-4 border-b dark:border-gray-700">
                    <h3 className="font-semibold text-lg">Bonus Tiers</h3>
                </div>
                <div className="p-6 space-y-4">
                    {editableTiers.sort((a,b) => a.threshold - b.threshold).map(tier => (
                        <div key={tier.id} className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                            <Input
                                label="Revenue Threshold ($)"
                                type="number"
                                value={String(tier.threshold)}
                                onChange={(e) => handleTierChange(tier.id, 'threshold', e.target.value)}
                            />
                            <Input
                                label="Bonus Percentage (%)"
                                type="number"
                                value={String(tier.bonusPercentage)}
                                onChange={(e) => handleTierChange(tier.id, 'bonusPercentage', e.target.value)}
                            />
                            <div className="flex items-end h-full">
                                <Button variant="danger" size="sm" onClick={() => handleDeleteTier(tier.id)} className="mt-auto">
                                    <Icon.Trash className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                    ))}
                </div>
                <div className="p-6 border-t dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
                    <h4 className="font-semibold mb-2">Add New Tier</h4>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                        <Input
                            label="Revenue Threshold ($)"
                            name="threshold"
                            type="number"
                            value={newTier.threshold}
                            onChange={handleNewTierChange}
                            placeholder="e.g., 50000"
                        />
                        <Input
                            label="Bonus Percentage (%)"
                            name="bonusPercentage"
                            type="number"
                            value={newTier.bonusPercentage}
                            onChange={handleNewTierChange}
                            placeholder="e.g., 5"
                        />
                         <div className="flex items-end h-full">
                            <Button onClick={handleAddTier} className="w-full md:w-auto">Add Tier</Button>
                        </div>
                    </div>
                </div>
            </Card>

            <div className="flex justify-end">
                <Button size="lg" onClick={handleSaveChanges}>
                    <Icon.Save className="w-5 h-5 mr-2" />
                    Save Changes
                </Button>
            </div>
        </div>
    );
};

export default RappelSettings;
